name: extensions_kit
description: An essential and powerful library of dart extensions to remove the
  boilerplate and speed up the development process.
version: 1.0.1
homepage: https://github.com/zainulabidin379/extensions_kit
repository: https://github.com/zainulabidin379/extensions_kit
documentation: https://extensionskitdocs.vercel.app/

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
